services:
  # Shorter segments for faster local testing
  archiver_manager:
    environment:
      SEGMENT_SECONDS: "60"
      # Keep it simple for E2E: record cam3 only (avoid RTSP 404 spam)
      CAMERA_LIST: "cam3=rtsp://mediamtx:8554/cam3"

  recording_indexer:
    environment:
      SEGMENT_SECONDS: "60"

  api_main:
    environment:
      - SEGMENT_SECONDS=60
      - MINIO_PUBLIC_BASE_URL=http://10.0.2.2:9000
      - MINIO_PUBLIC_ENDPOINT=http://10.0.2.2:9000
  # One-off test publisher for cam3 (start with: docker compose up -d test_publisher_cam3)
  test_publisher_cam3:
    image: jrottenberg/ffmpeg:5.1-alpine
    restart: unless-stopped
    depends_on: [mediamtx]
    networks: [cctv_network]
    command:
      - -re
      - -f
      - lavfi
      - -i
      - testsrc=size=640x360:rate=25
      - -f
      - lavfi
      - -i
      - sine=frequency=1000:sample_rate=48000
      - -c:v
      - libx264
      - -preset
      - veryfast
      - -tune
      - zerolatency
      - -pix_fmt
      - yuv420p
      - -profile:v
      - main
      - -g
      - "50"
      - -c:a
      - aac
      - -b:a
      - 128k
      - -f
      - rtsp
      - -rtsp_transport
      - tcp
      - rtsp://mediamtx:8554/cam3
