// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg2fEHUyTbaPYEmY_rDBLTIy30rV1vTEk',
    appId: '1:571000132978:web:e851d8c9724703121e79eb',
    messagingSenderId: '571000132978',
    projectId: 'anomeye',
    authDomain: 'anomeye.firebaseapp.com',
    storageBucket: 'anomeye.firebasestorage.app',
    measurementId: 'G-L8J6CJTYKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbUj6IyeBYCEoNtXiojZ6SwrAgV8UjbR4',
    appId: '1:571000132978:android:fd711bf28da9cb121e79eb',
    messagingSenderId: '571000132978',
    projectId: 'anomeye',
    storageBucket: 'anomeye.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoYqYXccD23Q-yGlFRRuieZcrBnQAn1Mk',
    appId: '1:571000132978:ios:a4358152379e76e61e79eb',
    messagingSenderId: '571000132978',
    projectId: 'anomeye',
    storageBucket: 'anomeye.firebasestorage.app',
    iosBundleId: 'com.example.anomeye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoYqYXccD23Q-yGlFRRuieZcrBnQAn1Mk',
    appId: '1:571000132978:ios:a4358152379e76e61e79eb',
    messagingSenderId: '571000132978',
    projectId: 'anomeye',
    storageBucket: 'anomeye.firebasestorage.app',
    iosBundleId: 'com.example.anomeye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg2fEHUyTbaPYEmY_rDBLTIy30rV1vTEk',
    appId: '1:571000132978:web:bd0ecb5f17c247281e79eb',
    messagingSenderId: '571000132978',
    projectId: 'anomeye',
    authDomain: 'anomeye.firebaseapp.com',
    storageBucket: 'anomeye.firebasestorage.app',
    measurementId: 'G-4DKP19LDPR',
  );
}
